title: Aaron Yan
description: Bioinformatics • ML • Imaging • Software
theme: minima

# Which pages appear in the top nav:
header_pages:
  - projects.md
  - publications.md
  - about.md

# Social links (replace with yours)
minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/yan-aaron" }
    - { platform: email,          user_url: "mailto:aarony3061@berkeley.com" }

